/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedGateRouteRouteImport } from './routes/_authenticated/gate/route'
import { Route as AuthenticatedLinkVillaRouteImport } from './routes/_authenticated/link-villa'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAmenitiesRouteImport } from './routes/_authenticated/admin/amenities'
import { Route as AuthenticatedAdminAnnualFeesRouteImport } from './routes/_authenticated/admin/annual-fees'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminBankAccountsRouteImport } from './routes/_authenticated/admin/bank-accounts'
import { Route as AuthenticatedAdminBankBulkEntryRouteImport } from './routes/_authenticated/admin/bank-bulk-entry'
import { Route as AuthenticatedAdminBankReconciliationRouteImport } from './routes/_authenticated/admin/bank-reconciliation'
import { Route as AuthenticatedAdminBankTransactionsRouteImport } from './routes/_authenticated/admin/bank-transactions'
import { Route as AuthenticatedAdminBulkEmailRouteImport } from './routes/_authenticated/admin/bulk-email'
import { Route as AuthenticatedAdminChartOfAccountsRouteImport } from './routes/_authenticated/admin/chart-of-accounts'
import { Route as AuthenticatedAdminCreditNotesRouteImport } from './routes/_authenticated/admin/credit-notes'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminEmergencyContactsRouteImport } from './routes/_authenticated/admin/emergency-contacts'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin/expenses'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin/invoices'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin/maintenance'
import { Route as AuthenticatedAdminNoticeGroupsRouteImport } from './routes/_authenticated/admin/notice-groups'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin/notices'
import { Route as AuthenticatedAdminOwnersAssociationRouteImport } from './routes/_authenticated/admin/owners-association'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminPayrollJournalsRouteImport } from './routes/_authenticated/admin/payroll-journals'
import { Route as AuthenticatedAdminPortalAccessRequestsRouteImport } from './routes/_authenticated/admin/portal-access-requests'
import { Route as AuthenticatedAdminPurchaseInvoicesRouteImport } from './routes/_authenticated/admin/purchase-invoices'
import { Route as AuthenticatedAdminPurchasesRouteImport } from './routes/_authenticated/admin/purchases'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminReportsHubRouteImport } from './routes/_authenticated/admin/reports-hub'
import { Route as AuthenticatedAdminResidentsRouteImport } from './routes/_authenticated/admin/residents'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin/sales'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminStatementsRouteImport } from './routes/_authenticated/admin/statements'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes/_authenticated/admin/units'
import { Route as AuthenticatedAdminVendorPaymentsRouteImport } from './routes/_authenticated/admin/vendor-payments'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin/vendors'
import { Route as AuthenticatedAdminVisitorsRouteImport } from './routes/_authenticated/admin/visitors'
import { Route as AuthenticatedGateIndexRouteImport } from './routes/_authenticated/gate/index'
import { Route as AuthenticatedGateApprovedRouteImport } from './routes/_authenticated/gate/approved'
import { Route as AuthenticatedGateCheckinRouteImport } from './routes/_authenticated/gate/checkin'
import { Route as AuthenticatedGateEmergencyRouteImport } from './routes/_authenticated/gate/emergency'
import { Route as AuthenticatedGateIncidentsRouteImport } from './routes/_authenticated/gate/incidents'
import { Route as AuthenticatedGateScanRouteImport } from './routes/_authenticated/gate/scan'
import { Route as AuthenticatedGateSearchRouteImport } from './routes/_authenticated/gate/search'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalAmenitiesRouteImport } from './routes/_authenticated/portal/amenities'
import { Route as AuthenticatedPortalAnnouncementsRouteImport } from './routes/_authenticated/portal/announcements'
import { Route as AuthenticatedPortalCalculatorRouteImport } from './routes/_authenticated/portal/calculator'
import { Route as AuthenticatedPortalInvoicesRouteImport } from './routes/_authenticated/portal/invoices'
import { Route as AuthenticatedPortalMaintenanceRouteImport } from './routes/_authenticated/portal/maintenance'
import { Route as AuthenticatedPortalMoreRouteImport } from './routes/_authenticated/portal/more'
import { Route as AuthenticatedPortalOwnersAssociationRouteImport } from './routes/_authenticated/portal/owners-association'
import { Route as AuthenticatedPortalVisitorsRouteImport } from './routes/_authenticated/portal/visitors'
import { Route as AuthenticatedPortalWorkRouteImport } from './routes/_authenticated/portal/work'
import { Route as AuthenticatedAdminHrAttendanceRouteImport } from './routes/_authenticated/admin/hr/attendance'
import { Route as AuthenticatedAdminHrConfigRouteImport } from './routes/_authenticated/admin/hr/config'
import { Route as AuthenticatedAdminHrEmployeesRouteImport } from './routes/_authenticated/admin/hr/employees'
import { Route as AuthenticatedAdminHrLeaveRouteImport } from './routes/_authenticated/admin/hr/leave'
import { Route as AuthenticatedAdminHrPayrollRouteImport } from './routes/_authenticated/admin/hr/payroll'
import { Route as AuthenticatedAdminHrPayslipsRouteImport } from './routes/_authenticated/admin/hr/payslips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGateRouteRoute = AuthenticatedGateRouteRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkVillaRoute = AuthenticatedLinkVillaRouteImport.update({
  id: '/link-villa',
  path: '/link-villa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAmenitiesRoute =
  AuthenticatedAdminAmenitiesRouteImport.update({
    id: '/amenities',
    path: '/amenities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnualFeesRoute =
  AuthenticatedAdminAnnualFeesRouteImport.update({
    id: '/annual-fees',
    path: '/annual-fees',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBankAccountsRoute =
  AuthenticatedAdminBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBankBulkEntryRoute =
  AuthenticatedAdminBankBulkEntryRouteImport.update({
    id: '/bank-bulk-entry',
    path: '/bank-bulk-entry',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBankReconciliationRoute =
  AuthenticatedAdminBankReconciliationRouteImport.update({
    id: '/bank-reconciliation',
    path: '/bank-reconciliation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBankTransactionsRoute =
  AuthenticatedAdminBankTransactionsRouteImport.update({
    id: '/bank-transactions',
    path: '/bank-transactions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBulkEmailRoute =
  AuthenticatedAdminBulkEmailRouteImport.update({
    id: '/bulk-email',
    path: '/bulk-email',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminChartOfAccountsRoute =
  AuthenticatedAdminChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCreditNotesRoute =
  AuthenticatedAdminCreditNotesRouteImport.update({
    id: '/credit-notes',
    path: '/credit-notes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmergencyContactsRoute =
  AuthenticatedAdminEmergencyContactsRouteImport.update({
    id: '/emergency-contacts',
    path: '/emergency-contacts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNoticeGroupsRoute =
  AuthenticatedAdminNoticeGroupsRouteImport.update({
    id: '/notice-groups',
    path: '/notice-groups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOwnersAssociationRoute =
  AuthenticatedAdminOwnersAssociationRouteImport.update({
    id: '/owners-association',
    path: '/owners-association',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPayrollJournalsRoute =
  AuthenticatedAdminPayrollJournalsRouteImport.update({
    id: '/payroll-journals',
    path: '/payroll-journals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPortalAccessRequestsRoute =
  AuthenticatedAdminPortalAccessRequestsRouteImport.update({
    id: '/portal-access-requests',
    path: '/portal-access-requests',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPurchaseInvoicesRoute =
  AuthenticatedAdminPurchaseInvoicesRouteImport.update({
    id: '/purchase-invoices',
    path: '/purchase-invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPurchasesRoute =
  AuthenticatedAdminPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsHubRoute =
  AuthenticatedAdminReportsHubRouteImport.update({
    id: '/reports-hub',
    path: '/reports-hub',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResidentsRoute =
  AuthenticatedAdminResidentsRouteImport.update({
    id: '/residents',
    path: '/residents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStatementsRoute =
  AuthenticatedAdminStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVendorPaymentsRoute =
  AuthenticatedAdminVendorPaymentsRouteImport.update({
    id: '/vendor-payments',
    path: '/vendor-payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVisitorsRoute =
  AuthenticatedAdminVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedGateIndexRoute = AuthenticatedGateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGateRouteRoute,
} as any)
const AuthenticatedGateApprovedRoute =
  AuthenticatedGateApprovedRouteImport.update({
    id: '/approved',
    path: '/approved',
    getParentRoute: () => AuthenticatedGateRouteRoute,
  } as any)
const AuthenticatedGateCheckinRoute =
  AuthenticatedGateCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedGateRouteRoute,
  } as any)
const AuthenticatedGateEmergencyRoute =
  AuthenticatedGateEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AuthenticatedGateRouteRoute,
  } as any)
const AuthenticatedGateIncidentsRoute =
  AuthenticatedGateIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedGateRouteRoute,
  } as any)
const AuthenticatedGateScanRoute = AuthenticatedGateScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedGateRouteRoute,
} as any)
const AuthenticatedGateSearchRoute = AuthenticatedGateSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedGateRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalAmenitiesRoute =
  AuthenticatedPortalAmenitiesRouteImport.update({
    id: '/amenities',
    path: '/amenities',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalAnnouncementsRoute =
  AuthenticatedPortalAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCalculatorRoute =
  AuthenticatedPortalCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalInvoicesRoute =
  AuthenticatedPortalInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMaintenanceRoute =
  AuthenticatedPortalMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMoreRoute = AuthenticatedPortalMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedPortalRouteRoute,
} as any)
const AuthenticatedPortalOwnersAssociationRoute =
  AuthenticatedPortalOwnersAssociationRouteImport.update({
    id: '/owners-association',
    path: '/owners-association',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalVisitorsRoute =
  AuthenticatedPortalVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalWorkRoute = AuthenticatedPortalWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedPortalRouteRoute,
} as any)
const AuthenticatedAdminHrAttendanceRoute =
  AuthenticatedAdminHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHrConfigRoute =
  AuthenticatedAdminHrConfigRouteImport.update({
    id: '/hr/config',
    path: '/hr/config',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHrEmployeesRoute =
  AuthenticatedAdminHrEmployeesRouteImport.update({
    id: '/hr/employees',
    path: '/hr/employees',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHrLeaveRoute =
  AuthenticatedAdminHrLeaveRouteImport.update({
    id: '/hr/leave',
    path: '/hr/leave',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHrPayrollRoute =
  AuthenticatedAdminHrPayrollRouteImport.update({
    id: '/hr/payroll',
    path: '/hr/payroll',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHrPayslipsRoute =
  AuthenticatedAdminHrPayslipsRouteImport.update({
    id: '/hr/payslips',
    path: '/hr/payslips',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/gate': typeof AuthenticatedGateRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/link-villa': typeof AuthenticatedLinkVillaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/admin/annual-fees': typeof AuthenticatedAdminAnnualFeesRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/admin/bank-bulk-entry': typeof AuthenticatedAdminBankBulkEntryRoute
  '/admin/bank-reconciliation': typeof AuthenticatedAdminBankReconciliationRoute
  '/admin/bank-transactions': typeof AuthenticatedAdminBankTransactionsRoute
  '/admin/bulk-email': typeof AuthenticatedAdminBulkEmailRoute
  '/admin/chart-of-accounts': typeof AuthenticatedAdminChartOfAccountsRoute
  '/admin/credit-notes': typeof AuthenticatedAdminCreditNotesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/emergency-contacts': typeof AuthenticatedAdminEmergencyContactsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/notice-groups': typeof AuthenticatedAdminNoticeGroupsRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/owners-association': typeof AuthenticatedAdminOwnersAssociationRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payroll-journals': typeof AuthenticatedAdminPayrollJournalsRoute
  '/admin/portal-access-requests': typeof AuthenticatedAdminPortalAccessRequestsRoute
  '/admin/purchase-invoices': typeof AuthenticatedAdminPurchaseInvoicesRoute
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reports-hub': typeof AuthenticatedAdminReportsHubRoute
  '/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/statements': typeof AuthenticatedAdminStatementsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/vendor-payments': typeof AuthenticatedAdminVendorPaymentsRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/gate/approved': typeof AuthenticatedGateApprovedRoute
  '/gate/checkin': typeof AuthenticatedGateCheckinRoute
  '/gate/emergency': typeof AuthenticatedGateEmergencyRoute
  '/gate/incidents': typeof AuthenticatedGateIncidentsRoute
  '/gate/scan': typeof AuthenticatedGateScanRoute
  '/gate/search': typeof AuthenticatedGateSearchRoute
  '/portal/amenities': typeof AuthenticatedPortalAmenitiesRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/calculator': typeof AuthenticatedPortalCalculatorRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/maintenance': typeof AuthenticatedPortalMaintenanceRoute
  '/portal/more': typeof AuthenticatedPortalMoreRoute
  '/portal/owners-association': typeof AuthenticatedPortalOwnersAssociationRoute
  '/portal/visitors': typeof AuthenticatedPortalVisitorsRoute
  '/portal/work': typeof AuthenticatedPortalWorkRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/gate/': typeof AuthenticatedGateIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/admin/hr/config': typeof AuthenticatedAdminHrConfigRoute
  '/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/admin/hr/leave': typeof AuthenticatedAdminHrLeaveRoute
  '/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/admin/hr/payslips': typeof AuthenticatedAdminHrPayslipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/link-villa': typeof AuthenticatedLinkVillaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/admin/annual-fees': typeof AuthenticatedAdminAnnualFeesRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/admin/bank-bulk-entry': typeof AuthenticatedAdminBankBulkEntryRoute
  '/admin/bank-reconciliation': typeof AuthenticatedAdminBankReconciliationRoute
  '/admin/bank-transactions': typeof AuthenticatedAdminBankTransactionsRoute
  '/admin/bulk-email': typeof AuthenticatedAdminBulkEmailRoute
  '/admin/chart-of-accounts': typeof AuthenticatedAdminChartOfAccountsRoute
  '/admin/credit-notes': typeof AuthenticatedAdminCreditNotesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/emergency-contacts': typeof AuthenticatedAdminEmergencyContactsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/notice-groups': typeof AuthenticatedAdminNoticeGroupsRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/owners-association': typeof AuthenticatedAdminOwnersAssociationRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payroll-journals': typeof AuthenticatedAdminPayrollJournalsRoute
  '/admin/portal-access-requests': typeof AuthenticatedAdminPortalAccessRequestsRoute
  '/admin/purchase-invoices': typeof AuthenticatedAdminPurchaseInvoicesRoute
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reports-hub': typeof AuthenticatedAdminReportsHubRoute
  '/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/statements': typeof AuthenticatedAdminStatementsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/vendor-payments': typeof AuthenticatedAdminVendorPaymentsRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/gate/approved': typeof AuthenticatedGateApprovedRoute
  '/gate/checkin': typeof AuthenticatedGateCheckinRoute
  '/gate/emergency': typeof AuthenticatedGateEmergencyRoute
  '/gate/incidents': typeof AuthenticatedGateIncidentsRoute
  '/gate/scan': typeof AuthenticatedGateScanRoute
  '/gate/search': typeof AuthenticatedGateSearchRoute
  '/portal/amenities': typeof AuthenticatedPortalAmenitiesRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/calculator': typeof AuthenticatedPortalCalculatorRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/maintenance': typeof AuthenticatedPortalMaintenanceRoute
  '/portal/more': typeof AuthenticatedPortalMoreRoute
  '/portal/owners-association': typeof AuthenticatedPortalOwnersAssociationRoute
  '/portal/visitors': typeof AuthenticatedPortalVisitorsRoute
  '/portal/work': typeof AuthenticatedPortalWorkRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/gate': typeof AuthenticatedGateIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/admin/hr/config': typeof AuthenticatedAdminHrConfigRoute
  '/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/admin/hr/leave': typeof AuthenticatedAdminHrLeaveRoute
  '/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/admin/hr/payslips': typeof AuthenticatedAdminHrPayslipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/gate': typeof AuthenticatedGateRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/link-villa': typeof AuthenticatedLinkVillaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/_authenticated/admin/annual-fees': typeof AuthenticatedAdminAnnualFeesRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/_authenticated/admin/bank-bulk-entry': typeof AuthenticatedAdminBankBulkEntryRoute
  '/_authenticated/admin/bank-reconciliation': typeof AuthenticatedAdminBankReconciliationRoute
  '/_authenticated/admin/bank-transactions': typeof AuthenticatedAdminBankTransactionsRoute
  '/_authenticated/admin/bulk-email': typeof AuthenticatedAdminBulkEmailRoute
  '/_authenticated/admin/chart-of-accounts': typeof AuthenticatedAdminChartOfAccountsRoute
  '/_authenticated/admin/credit-notes': typeof AuthenticatedAdminCreditNotesRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/emergency-contacts': typeof AuthenticatedAdminEmergencyContactsRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/notice-groups': typeof AuthenticatedAdminNoticeGroupsRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/owners-association': typeof AuthenticatedAdminOwnersAssociationRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payroll-journals': typeof AuthenticatedAdminPayrollJournalsRoute
  '/_authenticated/admin/portal-access-requests': typeof AuthenticatedAdminPortalAccessRequestsRoute
  '/_authenticated/admin/purchase-invoices': typeof AuthenticatedAdminPurchaseInvoicesRoute
  '/_authenticated/admin/purchases': typeof AuthenticatedAdminPurchasesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/reports-hub': typeof AuthenticatedAdminReportsHubRoute
  '/_authenticated/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/statements': typeof AuthenticatedAdminStatementsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/_authenticated/admin/vendor-payments': typeof AuthenticatedAdminVendorPaymentsRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/_authenticated/gate/approved': typeof AuthenticatedGateApprovedRoute
  '/_authenticated/gate/checkin': typeof AuthenticatedGateCheckinRoute
  '/_authenticated/gate/emergency': typeof AuthenticatedGateEmergencyRoute
  '/_authenticated/gate/incidents': typeof AuthenticatedGateIncidentsRoute
  '/_authenticated/gate/scan': typeof AuthenticatedGateScanRoute
  '/_authenticated/gate/search': typeof AuthenticatedGateSearchRoute
  '/_authenticated/portal/amenities': typeof AuthenticatedPortalAmenitiesRoute
  '/_authenticated/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/_authenticated/portal/calculator': typeof AuthenticatedPortalCalculatorRoute
  '/_authenticated/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/_authenticated/portal/maintenance': typeof AuthenticatedPortalMaintenanceRoute
  '/_authenticated/portal/more': typeof AuthenticatedPortalMoreRoute
  '/_authenticated/portal/owners-association': typeof AuthenticatedPortalOwnersAssociationRoute
  '/_authenticated/portal/visitors': typeof AuthenticatedPortalVisitorsRoute
  '/_authenticated/portal/work': typeof AuthenticatedPortalWorkRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/gate/': typeof AuthenticatedGateIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/_authenticated/admin/hr/config': typeof AuthenticatedAdminHrConfigRoute
  '/_authenticated/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/_authenticated/admin/hr/leave': typeof AuthenticatedAdminHrLeaveRoute
  '/_authenticated/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/_authenticated/admin/hr/payslips': typeof AuthenticatedAdminHrPayslipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/gate'
    | '/portal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/link-villa'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/amenities'
    | '/admin/annual-fees'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/bank-accounts'
    | '/admin/bank-bulk-entry'
    | '/admin/bank-reconciliation'
    | '/admin/bank-transactions'
    | '/admin/bulk-email'
    | '/admin/chart-of-accounts'
    | '/admin/credit-notes'
    | '/admin/documents'
    | '/admin/emergency-contacts'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/notice-groups'
    | '/admin/notices'
    | '/admin/owners-association'
    | '/admin/payments'
    | '/admin/payroll-journals'
    | '/admin/portal-access-requests'
    | '/admin/purchase-invoices'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/reports-hub'
    | '/admin/residents'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/statements'
    | '/admin/templates'
    | '/admin/units'
    | '/admin/vendor-payments'
    | '/admin/vendors'
    | '/admin/visitors'
    | '/gate/approved'
    | '/gate/checkin'
    | '/gate/emergency'
    | '/gate/incidents'
    | '/gate/scan'
    | '/gate/search'
    | '/portal/amenities'
    | '/portal/announcements'
    | '/portal/calculator'
    | '/portal/invoices'
    | '/portal/maintenance'
    | '/portal/more'
    | '/portal/owners-association'
    | '/portal/visitors'
    | '/portal/work'
    | '/admin/'
    | '/gate/'
    | '/portal/'
    | '/admin/hr/attendance'
    | '/admin/hr/config'
    | '/admin/hr/employees'
    | '/admin/hr/leave'
    | '/admin/hr/payroll'
    | '/admin/hr/payslips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/link-villa'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/amenities'
    | '/admin/annual-fees'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/bank-accounts'
    | '/admin/bank-bulk-entry'
    | '/admin/bank-reconciliation'
    | '/admin/bank-transactions'
    | '/admin/bulk-email'
    | '/admin/chart-of-accounts'
    | '/admin/credit-notes'
    | '/admin/documents'
    | '/admin/emergency-contacts'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/notice-groups'
    | '/admin/notices'
    | '/admin/owners-association'
    | '/admin/payments'
    | '/admin/payroll-journals'
    | '/admin/portal-access-requests'
    | '/admin/purchase-invoices'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/reports-hub'
    | '/admin/residents'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/statements'
    | '/admin/templates'
    | '/admin/units'
    | '/admin/vendor-payments'
    | '/admin/vendors'
    | '/admin/visitors'
    | '/gate/approved'
    | '/gate/checkin'
    | '/gate/emergency'
    | '/gate/incidents'
    | '/gate/scan'
    | '/gate/search'
    | '/portal/amenities'
    | '/portal/announcements'
    | '/portal/calculator'
    | '/portal/invoices'
    | '/portal/maintenance'
    | '/portal/more'
    | '/portal/owners-association'
    | '/portal/visitors'
    | '/portal/work'
    | '/admin'
    | '/gate'
    | '/portal'
    | '/admin/hr/attendance'
    | '/admin/hr/config'
    | '/admin/hr/employees'
    | '/admin/hr/leave'
    | '/admin/hr/payroll'
    | '/admin/hr/payslips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/gate'
    | '/_authenticated/portal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/link-villa'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/amenities'
    | '/_authenticated/admin/annual-fees'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bank-accounts'
    | '/_authenticated/admin/bank-bulk-entry'
    | '/_authenticated/admin/bank-reconciliation'
    | '/_authenticated/admin/bank-transactions'
    | '/_authenticated/admin/bulk-email'
    | '/_authenticated/admin/chart-of-accounts'
    | '/_authenticated/admin/credit-notes'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/emergency-contacts'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/notice-groups'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/owners-association'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payroll-journals'
    | '/_authenticated/admin/portal-access-requests'
    | '/_authenticated/admin/purchase-invoices'
    | '/_authenticated/admin/purchases'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/reports-hub'
    | '/_authenticated/admin/residents'
    | '/_authenticated/admin/sales'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/statements'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/units'
    | '/_authenticated/admin/vendor-payments'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/admin/visitors'
    | '/_authenticated/gate/approved'
    | '/_authenticated/gate/checkin'
    | '/_authenticated/gate/emergency'
    | '/_authenticated/gate/incidents'
    | '/_authenticated/gate/scan'
    | '/_authenticated/gate/search'
    | '/_authenticated/portal/amenities'
    | '/_authenticated/portal/announcements'
    | '/_authenticated/portal/calculator'
    | '/_authenticated/portal/invoices'
    | '/_authenticated/portal/maintenance'
    | '/_authenticated/portal/more'
    | '/_authenticated/portal/owners-association'
    | '/_authenticated/portal/visitors'
    | '/_authenticated/portal/work'
    | '/_authenticated/admin/'
    | '/_authenticated/gate/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/hr/attendance'
    | '/_authenticated/admin/hr/config'
    | '/_authenticated/admin/hr/employees'
    | '/_authenticated/admin/hr/leave'
    | '/_authenticated/admin/hr/payroll'
    | '/_authenticated/admin/hr/payslips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gate': {
      id: '/_authenticated/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof AuthenticatedGateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/link-villa': {
      id: '/_authenticated/link-villa'
      path: '/link-villa'
      fullPath: '/link-villa'
      preLoaderRoute: typeof AuthenticatedLinkVillaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/amenities': {
      id: '/_authenticated/admin/amenities'
      path: '/amenities'
      fullPath: '/admin/amenities'
      preLoaderRoute: typeof AuthenticatedAdminAmenitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/annual-fees': {
      id: '/_authenticated/admin/annual-fees'
      path: '/annual-fees'
      fullPath: '/admin/annual-fees'
      preLoaderRoute: typeof AuthenticatedAdminAnnualFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bank-accounts': {
      id: '/_authenticated/admin/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/admin/bank-accounts'
      preLoaderRoute: typeof AuthenticatedAdminBankAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bank-bulk-entry': {
      id: '/_authenticated/admin/bank-bulk-entry'
      path: '/bank-bulk-entry'
      fullPath: '/admin/bank-bulk-entry'
      preLoaderRoute: typeof AuthenticatedAdminBankBulkEntryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bank-reconciliation': {
      id: '/_authenticated/admin/bank-reconciliation'
      path: '/bank-reconciliation'
      fullPath: '/admin/bank-reconciliation'
      preLoaderRoute: typeof AuthenticatedAdminBankReconciliationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bank-transactions': {
      id: '/_authenticated/admin/bank-transactions'
      path: '/bank-transactions'
      fullPath: '/admin/bank-transactions'
      preLoaderRoute: typeof AuthenticatedAdminBankTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bulk-email': {
      id: '/_authenticated/admin/bulk-email'
      path: '/bulk-email'
      fullPath: '/admin/bulk-email'
      preLoaderRoute: typeof AuthenticatedAdminBulkEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/chart-of-accounts': {
      id: '/_authenticated/admin/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/admin/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedAdminChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/credit-notes': {
      id: '/_authenticated/admin/credit-notes'
      path: '/credit-notes'
      fullPath: '/admin/credit-notes'
      preLoaderRoute: typeof AuthenticatedAdminCreditNotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/emergency-contacts': {
      id: '/_authenticated/admin/emergency-contacts'
      path: '/emergency-contacts'
      fullPath: '/admin/emergency-contacts'
      preLoaderRoute: typeof AuthenticatedAdminEmergencyContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notice-groups': {
      id: '/_authenticated/admin/notice-groups'
      path: '/notice-groups'
      fullPath: '/admin/notice-groups'
      preLoaderRoute: typeof AuthenticatedAdminNoticeGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/owners-association': {
      id: '/_authenticated/admin/owners-association'
      path: '/owners-association'
      fullPath: '/admin/owners-association'
      preLoaderRoute: typeof AuthenticatedAdminOwnersAssociationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payroll-journals': {
      id: '/_authenticated/admin/payroll-journals'
      path: '/payroll-journals'
      fullPath: '/admin/payroll-journals'
      preLoaderRoute: typeof AuthenticatedAdminPayrollJournalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/portal-access-requests': {
      id: '/_authenticated/admin/portal-access-requests'
      path: '/portal-access-requests'
      fullPath: '/admin/portal-access-requests'
      preLoaderRoute: typeof AuthenticatedAdminPortalAccessRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/purchase-invoices': {
      id: '/_authenticated/admin/purchase-invoices'
      path: '/purchase-invoices'
      fullPath: '/admin/purchase-invoices'
      preLoaderRoute: typeof AuthenticatedAdminPurchaseInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/purchases': {
      id: '/_authenticated/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AuthenticatedAdminPurchasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports-hub': {
      id: '/_authenticated/admin/reports-hub'
      path: '/reports-hub'
      fullPath: '/admin/reports-hub'
      preLoaderRoute: typeof AuthenticatedAdminReportsHubRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/residents': {
      id: '/_authenticated/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AuthenticatedAdminResidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/statements': {
      id: '/_authenticated/admin/statements'
      path: '/statements'
      fullPath: '/admin/statements'
      preLoaderRoute: typeof AuthenticatedAdminStatementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units': {
      id: '/_authenticated/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vendor-payments': {
      id: '/_authenticated/admin/vendor-payments'
      path: '/vendor-payments'
      fullPath: '/admin/vendor-payments'
      preLoaderRoute: typeof AuthenticatedAdminVendorPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/visitors': {
      id: '/_authenticated/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AuthenticatedAdminVisitorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/gate/': {
      id: '/_authenticated/gate/'
      path: '/'
      fullPath: '/gate/'
      preLoaderRoute: typeof AuthenticatedGateIndexRouteImport
      parentRoute: typeof AuthenticatedGateRouteRoute
    }
    '/_authenticated/gate/approved': {
      id: '/_authenticated/gate/approved'
      path: '/approved'
      fullPath: '/gate/approved'
      preLoaderRoute: typeof AuthenticatedGateApprovedRouteImport
      parentRoute: typeof AuthenticatedGateRouteRoute
    }
    '/_authenticated/gate/checkin': {
      id: '/_authenticated/gate/checkin'
      path: '/checkin'
      fullPath: '/gate/checkin'
      preLoaderRoute: typeof AuthenticatedGateCheckinRouteImport
      parentRoute: typeof AuthenticatedGateRouteRoute
    }
    '/_authenticated/gate/emergency': {
      id: '/_authenticated/gate/emergency'
      path: '/emergency'
      fullPath: '/gate/emergency'
      preLoaderRoute: typeof AuthenticatedGateEmergencyRouteImport
      parentRoute: typeof AuthenticatedGateRouteRoute
    }
    '/_authenticated/gate/incidents': {
      id: '/_authenticated/gate/incidents'
      path: '/incidents'
      fullPath: '/gate/incidents'
      preLoaderRoute: typeof AuthenticatedGateIncidentsRouteImport
      parentRoute: typeof AuthenticatedGateRouteRoute
    }
    '/_authenticated/gate/scan': {
      id: '/_authenticated/gate/scan'
      path: '/scan'
      fullPath: '/gate/scan'
      preLoaderRoute: typeof AuthenticatedGateScanRouteImport
      parentRoute: typeof AuthenticatedGateRouteRoute
    }
    '/_authenticated/gate/search': {
      id: '/_authenticated/gate/search'
      path: '/search'
      fullPath: '/gate/search'
      preLoaderRoute: typeof AuthenticatedGateSearchRouteImport
      parentRoute: typeof AuthenticatedGateRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/amenities': {
      id: '/_authenticated/portal/amenities'
      path: '/amenities'
      fullPath: '/portal/amenities'
      preLoaderRoute: typeof AuthenticatedPortalAmenitiesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/announcements': {
      id: '/_authenticated/portal/announcements'
      path: '/announcements'
      fullPath: '/portal/announcements'
      preLoaderRoute: typeof AuthenticatedPortalAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/calculator': {
      id: '/_authenticated/portal/calculator'
      path: '/calculator'
      fullPath: '/portal/calculator'
      preLoaderRoute: typeof AuthenticatedPortalCalculatorRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/invoices': {
      id: '/_authenticated/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/maintenance': {
      id: '/_authenticated/portal/maintenance'
      path: '/maintenance'
      fullPath: '/portal/maintenance'
      preLoaderRoute: typeof AuthenticatedPortalMaintenanceRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/more': {
      id: '/_authenticated/portal/more'
      path: '/more'
      fullPath: '/portal/more'
      preLoaderRoute: typeof AuthenticatedPortalMoreRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/owners-association': {
      id: '/_authenticated/portal/owners-association'
      path: '/owners-association'
      fullPath: '/portal/owners-association'
      preLoaderRoute: typeof AuthenticatedPortalOwnersAssociationRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/visitors': {
      id: '/_authenticated/portal/visitors'
      path: '/visitors'
      fullPath: '/portal/visitors'
      preLoaderRoute: typeof AuthenticatedPortalVisitorsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/work': {
      id: '/_authenticated/portal/work'
      path: '/work'
      fullPath: '/portal/work'
      preLoaderRoute: typeof AuthenticatedPortalWorkRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/hr/attendance': {
      id: '/_authenticated/admin/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/admin/hr/attendance'
      preLoaderRoute: typeof AuthenticatedAdminHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hr/config': {
      id: '/_authenticated/admin/hr/config'
      path: '/hr/config'
      fullPath: '/admin/hr/config'
      preLoaderRoute: typeof AuthenticatedAdminHrConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hr/employees': {
      id: '/_authenticated/admin/hr/employees'
      path: '/hr/employees'
      fullPath: '/admin/hr/employees'
      preLoaderRoute: typeof AuthenticatedAdminHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hr/leave': {
      id: '/_authenticated/admin/hr/leave'
      path: '/hr/leave'
      fullPath: '/admin/hr/leave'
      preLoaderRoute: typeof AuthenticatedAdminHrLeaveRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hr/payroll': {
      id: '/_authenticated/admin/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/admin/hr/payroll'
      preLoaderRoute: typeof AuthenticatedAdminHrPayrollRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hr/payslips': {
      id: '/_authenticated/admin/hr/payslips'
      path: '/hr/payslips'
      fullPath: '/admin/hr/payslips'
      preLoaderRoute: typeof AuthenticatedAdminHrPayslipsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAmenitiesRoute: typeof AuthenticatedAdminAmenitiesRoute
  AuthenticatedAdminAnnualFeesRoute: typeof AuthenticatedAdminAnnualFeesRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBankAccountsRoute: typeof AuthenticatedAdminBankAccountsRoute
  AuthenticatedAdminBankBulkEntryRoute: typeof AuthenticatedAdminBankBulkEntryRoute
  AuthenticatedAdminBankReconciliationRoute: typeof AuthenticatedAdminBankReconciliationRoute
  AuthenticatedAdminBankTransactionsRoute: typeof AuthenticatedAdminBankTransactionsRoute
  AuthenticatedAdminBulkEmailRoute: typeof AuthenticatedAdminBulkEmailRoute
  AuthenticatedAdminChartOfAccountsRoute: typeof AuthenticatedAdminChartOfAccountsRoute
  AuthenticatedAdminCreditNotesRoute: typeof AuthenticatedAdminCreditNotesRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminEmergencyContactsRoute: typeof AuthenticatedAdminEmergencyContactsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminNoticeGroupsRoute: typeof AuthenticatedAdminNoticeGroupsRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminOwnersAssociationRoute: typeof AuthenticatedAdminOwnersAssociationRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayrollJournalsRoute: typeof AuthenticatedAdminPayrollJournalsRoute
  AuthenticatedAdminPortalAccessRequestsRoute: typeof AuthenticatedAdminPortalAccessRequestsRoute
  AuthenticatedAdminPurchaseInvoicesRoute: typeof AuthenticatedAdminPurchaseInvoicesRoute
  AuthenticatedAdminPurchasesRoute: typeof AuthenticatedAdminPurchasesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminReportsHubRoute: typeof AuthenticatedAdminReportsHubRoute
  AuthenticatedAdminResidentsRoute: typeof AuthenticatedAdminResidentsRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStatementsRoute: typeof AuthenticatedAdminStatementsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRoute
  AuthenticatedAdminVendorPaymentsRoute: typeof AuthenticatedAdminVendorPaymentsRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminVisitorsRoute: typeof AuthenticatedAdminVisitorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminHrAttendanceRoute: typeof AuthenticatedAdminHrAttendanceRoute
  AuthenticatedAdminHrConfigRoute: typeof AuthenticatedAdminHrConfigRoute
  AuthenticatedAdminHrEmployeesRoute: typeof AuthenticatedAdminHrEmployeesRoute
  AuthenticatedAdminHrLeaveRoute: typeof AuthenticatedAdminHrLeaveRoute
  AuthenticatedAdminHrPayrollRoute: typeof AuthenticatedAdminHrPayrollRoute
  AuthenticatedAdminHrPayslipsRoute: typeof AuthenticatedAdminHrPayslipsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAmenitiesRoute: AuthenticatedAdminAmenitiesRoute,
    AuthenticatedAdminAnnualFeesRoute: AuthenticatedAdminAnnualFeesRoute,
    AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBankAccountsRoute: AuthenticatedAdminBankAccountsRoute,
    AuthenticatedAdminBankBulkEntryRoute: AuthenticatedAdminBankBulkEntryRoute,
    AuthenticatedAdminBankReconciliationRoute:
      AuthenticatedAdminBankReconciliationRoute,
    AuthenticatedAdminBankTransactionsRoute:
      AuthenticatedAdminBankTransactionsRoute,
    AuthenticatedAdminBulkEmailRoute: AuthenticatedAdminBulkEmailRoute,
    AuthenticatedAdminChartOfAccountsRoute:
      AuthenticatedAdminChartOfAccountsRoute,
    AuthenticatedAdminCreditNotesRoute: AuthenticatedAdminCreditNotesRoute,
    AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
    AuthenticatedAdminEmergencyContactsRoute:
      AuthenticatedAdminEmergencyContactsRoute,
    AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
    AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
    AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
    AuthenticatedAdminNoticeGroupsRoute: AuthenticatedAdminNoticeGroupsRoute,
    AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
    AuthenticatedAdminOwnersAssociationRoute:
      AuthenticatedAdminOwnersAssociationRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPayrollJournalsRoute:
      AuthenticatedAdminPayrollJournalsRoute,
    AuthenticatedAdminPortalAccessRequestsRoute:
      AuthenticatedAdminPortalAccessRequestsRoute,
    AuthenticatedAdminPurchaseInvoicesRoute:
      AuthenticatedAdminPurchaseInvoicesRoute,
    AuthenticatedAdminPurchasesRoute: AuthenticatedAdminPurchasesRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminReportsHubRoute: AuthenticatedAdminReportsHubRoute,
    AuthenticatedAdminResidentsRoute: AuthenticatedAdminResidentsRoute,
    AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStatementsRoute: AuthenticatedAdminStatementsRoute,
    AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
    AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRoute,
    AuthenticatedAdminVendorPaymentsRoute:
      AuthenticatedAdminVendorPaymentsRoute,
    AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
    AuthenticatedAdminVisitorsRoute: AuthenticatedAdminVisitorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminHrAttendanceRoute: AuthenticatedAdminHrAttendanceRoute,
    AuthenticatedAdminHrConfigRoute: AuthenticatedAdminHrConfigRoute,
    AuthenticatedAdminHrEmployeesRoute: AuthenticatedAdminHrEmployeesRoute,
    AuthenticatedAdminHrLeaveRoute: AuthenticatedAdminHrLeaveRoute,
    AuthenticatedAdminHrPayrollRoute: AuthenticatedAdminHrPayrollRoute,
    AuthenticatedAdminHrPayslipsRoute: AuthenticatedAdminHrPayslipsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedGateRouteRouteChildren {
  AuthenticatedGateApprovedRoute: typeof AuthenticatedGateApprovedRoute
  AuthenticatedGateCheckinRoute: typeof AuthenticatedGateCheckinRoute
  AuthenticatedGateEmergencyRoute: typeof AuthenticatedGateEmergencyRoute
  AuthenticatedGateIncidentsRoute: typeof AuthenticatedGateIncidentsRoute
  AuthenticatedGateScanRoute: typeof AuthenticatedGateScanRoute
  AuthenticatedGateSearchRoute: typeof AuthenticatedGateSearchRoute
  AuthenticatedGateIndexRoute: typeof AuthenticatedGateIndexRoute
}

const AuthenticatedGateRouteRouteChildren: AuthenticatedGateRouteRouteChildren =
  {
    AuthenticatedGateApprovedRoute: AuthenticatedGateApprovedRoute,
    AuthenticatedGateCheckinRoute: AuthenticatedGateCheckinRoute,
    AuthenticatedGateEmergencyRoute: AuthenticatedGateEmergencyRoute,
    AuthenticatedGateIncidentsRoute: AuthenticatedGateIncidentsRoute,
    AuthenticatedGateScanRoute: AuthenticatedGateScanRoute,
    AuthenticatedGateSearchRoute: AuthenticatedGateSearchRoute,
    AuthenticatedGateIndexRoute: AuthenticatedGateIndexRoute,
  }

const AuthenticatedGateRouteRouteWithChildren =
  AuthenticatedGateRouteRoute._addFileChildren(
    AuthenticatedGateRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalAmenitiesRoute: typeof AuthenticatedPortalAmenitiesRoute
  AuthenticatedPortalAnnouncementsRoute: typeof AuthenticatedPortalAnnouncementsRoute
  AuthenticatedPortalCalculatorRoute: typeof AuthenticatedPortalCalculatorRoute
  AuthenticatedPortalInvoicesRoute: typeof AuthenticatedPortalInvoicesRoute
  AuthenticatedPortalMaintenanceRoute: typeof AuthenticatedPortalMaintenanceRoute
  AuthenticatedPortalMoreRoute: typeof AuthenticatedPortalMoreRoute
  AuthenticatedPortalOwnersAssociationRoute: typeof AuthenticatedPortalOwnersAssociationRoute
  AuthenticatedPortalVisitorsRoute: typeof AuthenticatedPortalVisitorsRoute
  AuthenticatedPortalWorkRoute: typeof AuthenticatedPortalWorkRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalAmenitiesRoute: AuthenticatedPortalAmenitiesRoute,
    AuthenticatedPortalAnnouncementsRoute:
      AuthenticatedPortalAnnouncementsRoute,
    AuthenticatedPortalCalculatorRoute: AuthenticatedPortalCalculatorRoute,
    AuthenticatedPortalInvoicesRoute: AuthenticatedPortalInvoicesRoute,
    AuthenticatedPortalMaintenanceRoute: AuthenticatedPortalMaintenanceRoute,
    AuthenticatedPortalMoreRoute: AuthenticatedPortalMoreRoute,
    AuthenticatedPortalOwnersAssociationRoute:
      AuthenticatedPortalOwnersAssociationRoute,
    AuthenticatedPortalVisitorsRoute: AuthenticatedPortalVisitorsRoute,
    AuthenticatedPortalWorkRoute: AuthenticatedPortalWorkRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedGateRouteRoute: typeof AuthenticatedGateRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
  AuthenticatedLinkVillaRoute: typeof AuthenticatedLinkVillaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedGateRouteRoute: AuthenticatedGateRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
  AuthenticatedLinkVillaRoute: AuthenticatedLinkVillaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
