/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPortalVisitorsRouteImport } from './routes/_authenticated/portal/visitors'
import { Route as AuthenticatedPortalMoreRouteImport } from './routes/_authenticated/portal/more'
import { Route as AuthenticatedPortalMaintenanceRouteImport } from './routes/_authenticated/portal/maintenance'
import { Route as AuthenticatedPortalInvoicesRouteImport } from './routes/_authenticated/portal/invoices'
import { Route as AuthenticatedPortalCalculatorRouteImport } from './routes/_authenticated/portal/calculator'
import { Route as AuthenticatedPortalAnnouncementsRouteImport } from './routes/_authenticated/portal/announcements'
import { Route as AuthenticatedPortalAmenitiesRouteImport } from './routes/_authenticated/portal/amenities'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin/vendors'
import { Route as AuthenticatedAdminVendorPaymentsRouteImport } from './routes/_authenticated/admin/vendor-payments'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes/_authenticated/admin/units'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminStatementsRouteImport } from './routes/_authenticated/admin/statements'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin/sales'
import { Route as AuthenticatedAdminResidentsRouteImport } from './routes/_authenticated/admin/residents'
import { Route as AuthenticatedAdminPurchasesRouteImport } from './routes/_authenticated/admin/purchases'
import { Route as AuthenticatedAdminPurchaseReportsRouteImport } from './routes/_authenticated/admin/purchase-reports'
import { Route as AuthenticatedAdminPurchaseInvoicesRouteImport } from './routes/_authenticated/admin/purchase-invoices'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin/invoices'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin/expenses'
import { Route as AuthenticatedAdminCreditNotesRouteImport } from './routes/_authenticated/admin/credit-notes'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAmenitiesRouteImport } from './routes/_authenticated/admin/amenities'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPortalVisitorsRoute =
  AuthenticatedPortalVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMoreRoute = AuthenticatedPortalMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedPortalRouteRoute,
} as any)
const AuthenticatedPortalMaintenanceRoute =
  AuthenticatedPortalMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalInvoicesRoute =
  AuthenticatedPortalInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCalculatorRoute =
  AuthenticatedPortalCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalAnnouncementsRoute =
  AuthenticatedPortalAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalAmenitiesRoute =
  AuthenticatedPortalAmenitiesRouteImport.update({
    id: '/amenities',
    path: '/amenities',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVendorPaymentsRoute =
  AuthenticatedAdminVendorPaymentsRouteImport.update({
    id: '/vendor-payments',
    path: '/vendor-payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStatementsRoute =
  AuthenticatedAdminStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminResidentsRoute =
  AuthenticatedAdminResidentsRouteImport.update({
    id: '/residents',
    path: '/residents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPurchasesRoute =
  AuthenticatedAdminPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPurchaseReportsRoute =
  AuthenticatedAdminPurchaseReportsRouteImport.update({
    id: '/purchase-reports',
    path: '/purchase-reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPurchaseInvoicesRoute =
  AuthenticatedAdminPurchaseInvoicesRouteImport.update({
    id: '/purchase-invoices',
    path: '/purchase-invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCreditNotesRoute =
  AuthenticatedAdminCreditNotesRouteImport.update({
    id: '/credit-notes',
    path: '/credit-notes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAmenitiesRoute =
  AuthenticatedAdminAmenitiesRouteImport.update({
    id: '/amenities',
    path: '/amenities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/credit-notes': typeof AuthenticatedAdminCreditNotesRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/purchase-invoices': typeof AuthenticatedAdminPurchaseInvoicesRoute
  '/admin/purchase-reports': typeof AuthenticatedAdminPurchaseReportsRoute
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRoute
  '/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/statements': typeof AuthenticatedAdminStatementsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/vendor-payments': typeof AuthenticatedAdminVendorPaymentsRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/portal/amenities': typeof AuthenticatedPortalAmenitiesRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/calculator': typeof AuthenticatedPortalCalculatorRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/maintenance': typeof AuthenticatedPortalMaintenanceRoute
  '/portal/more': typeof AuthenticatedPortalMoreRoute
  '/portal/visitors': typeof AuthenticatedPortalVisitorsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/credit-notes': typeof AuthenticatedAdminCreditNotesRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/purchase-invoices': typeof AuthenticatedAdminPurchaseInvoicesRoute
  '/admin/purchase-reports': typeof AuthenticatedAdminPurchaseReportsRoute
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRoute
  '/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/statements': typeof AuthenticatedAdminStatementsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/vendor-payments': typeof AuthenticatedAdminVendorPaymentsRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/portal/amenities': typeof AuthenticatedPortalAmenitiesRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/calculator': typeof AuthenticatedPortalCalculatorRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/maintenance': typeof AuthenticatedPortalMaintenanceRoute
  '/portal/more': typeof AuthenticatedPortalMoreRoute
  '/portal/visitors': typeof AuthenticatedPortalVisitorsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/credit-notes': typeof AuthenticatedAdminCreditNotesRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/purchase-invoices': typeof AuthenticatedAdminPurchaseInvoicesRoute
  '/_authenticated/admin/purchase-reports': typeof AuthenticatedAdminPurchaseReportsRoute
  '/_authenticated/admin/purchases': typeof AuthenticatedAdminPurchasesRoute
  '/_authenticated/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/statements': typeof AuthenticatedAdminStatementsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/_authenticated/admin/vendor-payments': typeof AuthenticatedAdminVendorPaymentsRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/portal/amenities': typeof AuthenticatedPortalAmenitiesRoute
  '/_authenticated/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/_authenticated/portal/calculator': typeof AuthenticatedPortalCalculatorRoute
  '/_authenticated/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/_authenticated/portal/maintenance': typeof AuthenticatedPortalMaintenanceRoute
  '/_authenticated/portal/more': typeof AuthenticatedPortalMoreRoute
  '/_authenticated/portal/visitors': typeof AuthenticatedPortalVisitorsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/portal'
    | '/admin/amenities'
    | '/admin/audit'
    | '/admin/credit-notes'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/purchase-invoices'
    | '/admin/purchase-reports'
    | '/admin/purchases'
    | '/admin/residents'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/statements'
    | '/admin/templates'
    | '/admin/units'
    | '/admin/vendor-payments'
    | '/admin/vendors'
    | '/portal/amenities'
    | '/portal/announcements'
    | '/portal/calculator'
    | '/portal/invoices'
    | '/portal/maintenance'
    | '/portal/more'
    | '/portal/visitors'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/amenities'
    | '/admin/audit'
    | '/admin/credit-notes'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/purchase-invoices'
    | '/admin/purchase-reports'
    | '/admin/purchases'
    | '/admin/residents'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/statements'
    | '/admin/templates'
    | '/admin/units'
    | '/admin/vendor-payments'
    | '/admin/vendors'
    | '/portal/amenities'
    | '/portal/announcements'
    | '/portal/calculator'
    | '/portal/invoices'
    | '/portal/maintenance'
    | '/portal/more'
    | '/portal/visitors'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/admin/amenities'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/credit-notes'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/purchase-invoices'
    | '/_authenticated/admin/purchase-reports'
    | '/_authenticated/admin/purchases'
    | '/_authenticated/admin/residents'
    | '/_authenticated/admin/sales'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/statements'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/units'
    | '/_authenticated/admin/vendor-payments'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/portal/amenities'
    | '/_authenticated/portal/announcements'
    | '/_authenticated/portal/calculator'
    | '/_authenticated/portal/invoices'
    | '/_authenticated/portal/maintenance'
    | '/_authenticated/portal/more'
    | '/_authenticated/portal/visitors'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portal/visitors': {
      id: '/_authenticated/portal/visitors'
      path: '/visitors'
      fullPath: '/portal/visitors'
      preLoaderRoute: typeof AuthenticatedPortalVisitorsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/more': {
      id: '/_authenticated/portal/more'
      path: '/more'
      fullPath: '/portal/more'
      preLoaderRoute: typeof AuthenticatedPortalMoreRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/maintenance': {
      id: '/_authenticated/portal/maintenance'
      path: '/maintenance'
      fullPath: '/portal/maintenance'
      preLoaderRoute: typeof AuthenticatedPortalMaintenanceRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/invoices': {
      id: '/_authenticated/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/calculator': {
      id: '/_authenticated/portal/calculator'
      path: '/calculator'
      fullPath: '/portal/calculator'
      preLoaderRoute: typeof AuthenticatedPortalCalculatorRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/announcements': {
      id: '/_authenticated/portal/announcements'
      path: '/announcements'
      fullPath: '/portal/announcements'
      preLoaderRoute: typeof AuthenticatedPortalAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/amenities': {
      id: '/_authenticated/portal/amenities'
      path: '/amenities'
      fullPath: '/portal/amenities'
      preLoaderRoute: typeof AuthenticatedPortalAmenitiesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vendor-payments': {
      id: '/_authenticated/admin/vendor-payments'
      path: '/vendor-payments'
      fullPath: '/admin/vendor-payments'
      preLoaderRoute: typeof AuthenticatedAdminVendorPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units': {
      id: '/_authenticated/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/statements': {
      id: '/_authenticated/admin/statements'
      path: '/statements'
      fullPath: '/admin/statements'
      preLoaderRoute: typeof AuthenticatedAdminStatementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/residents': {
      id: '/_authenticated/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AuthenticatedAdminResidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/purchases': {
      id: '/_authenticated/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AuthenticatedAdminPurchasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/purchase-reports': {
      id: '/_authenticated/admin/purchase-reports'
      path: '/purchase-reports'
      fullPath: '/admin/purchase-reports'
      preLoaderRoute: typeof AuthenticatedAdminPurchaseReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/purchase-invoices': {
      id: '/_authenticated/admin/purchase-invoices'
      path: '/purchase-invoices'
      fullPath: '/admin/purchase-invoices'
      preLoaderRoute: typeof AuthenticatedAdminPurchaseInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/credit-notes': {
      id: '/_authenticated/admin/credit-notes'
      path: '/credit-notes'
      fullPath: '/admin/credit-notes'
      preLoaderRoute: typeof AuthenticatedAdminCreditNotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/amenities': {
      id: '/_authenticated/admin/amenities'
      path: '/amenities'
      fullPath: '/admin/amenities'
      preLoaderRoute: typeof AuthenticatedAdminAmenitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAmenitiesRoute: typeof AuthenticatedAdminAmenitiesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCreditNotesRoute: typeof AuthenticatedAdminCreditNotesRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPurchaseInvoicesRoute: typeof AuthenticatedAdminPurchaseInvoicesRoute
  AuthenticatedAdminPurchaseReportsRoute: typeof AuthenticatedAdminPurchaseReportsRoute
  AuthenticatedAdminPurchasesRoute: typeof AuthenticatedAdminPurchasesRoute
  AuthenticatedAdminResidentsRoute: typeof AuthenticatedAdminResidentsRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStatementsRoute: typeof AuthenticatedAdminStatementsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRoute
  AuthenticatedAdminVendorPaymentsRoute: typeof AuthenticatedAdminVendorPaymentsRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAmenitiesRoute: AuthenticatedAdminAmenitiesRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminCreditNotesRoute: AuthenticatedAdminCreditNotesRoute,
    AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
    AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPurchaseInvoicesRoute:
      AuthenticatedAdminPurchaseInvoicesRoute,
    AuthenticatedAdminPurchaseReportsRoute:
      AuthenticatedAdminPurchaseReportsRoute,
    AuthenticatedAdminPurchasesRoute: AuthenticatedAdminPurchasesRoute,
    AuthenticatedAdminResidentsRoute: AuthenticatedAdminResidentsRoute,
    AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStatementsRoute: AuthenticatedAdminStatementsRoute,
    AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
    AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRoute,
    AuthenticatedAdminVendorPaymentsRoute:
      AuthenticatedAdminVendorPaymentsRoute,
    AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalAmenitiesRoute: typeof AuthenticatedPortalAmenitiesRoute
  AuthenticatedPortalAnnouncementsRoute: typeof AuthenticatedPortalAnnouncementsRoute
  AuthenticatedPortalCalculatorRoute: typeof AuthenticatedPortalCalculatorRoute
  AuthenticatedPortalInvoicesRoute: typeof AuthenticatedPortalInvoicesRoute
  AuthenticatedPortalMaintenanceRoute: typeof AuthenticatedPortalMaintenanceRoute
  AuthenticatedPortalMoreRoute: typeof AuthenticatedPortalMoreRoute
  AuthenticatedPortalVisitorsRoute: typeof AuthenticatedPortalVisitorsRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalAmenitiesRoute: AuthenticatedPortalAmenitiesRoute,
    AuthenticatedPortalAnnouncementsRoute:
      AuthenticatedPortalAnnouncementsRoute,
    AuthenticatedPortalCalculatorRoute: AuthenticatedPortalCalculatorRoute,
    AuthenticatedPortalInvoicesRoute: AuthenticatedPortalInvoicesRoute,
    AuthenticatedPortalMaintenanceRoute: AuthenticatedPortalMaintenanceRoute,
    AuthenticatedPortalMoreRoute: AuthenticatedPortalMoreRoute,
    AuthenticatedPortalVisitorsRoute: AuthenticatedPortalVisitorsRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
